Initial code commit
salesforce/refocus-whitelist pull request #1
Opened 2019-04-15 21:29 UTC by iamigo

When you review this, please also double-check to make sure there is nothing in this repo which could prevent us from making it public.

2019-04-15 23:07 UTC, pallavi2209 requested changes

2019-04-15 23:07 UTC, pallavi2209 commented on test/common.js
> +describe('test/common.js > ', () => {
empty - this is intentional?

2019-04-15 23:07 UTC, pallavi2209 commented on test/whitelistUtils.js
> +      expect(isWhitelisted('123.0.0.100', w)).to.be.true;
Is there a test for a case when an empty or a null string is passed?

2019-04-15 23:25 UTC, iamigo commented on test/whitelistUtils.js
> +      expect(isWhitelisted('123.0.0.100', w)).to.be.true;
In the usage pattern here, this is guaranteed to be a string which looks like a valid ipv4 string because that is already enforced by the express routing parameter regular expression, so I didn't bother testing scenarios where it's not a string or not a valid ipv4.

2019-04-17 21:39 UTC, pallavi2209 approved these changes

2019-04-17 21:57 UTC, merged